config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post 'play/play', to: 'play#play', as: 'play_play'
  post 'play/entries/:game_player_card_id', to: 'play#entries', as: 'play_entries'
  get 'play/:locator', to: 'play#join', as: 'play_join'
  resources :players
  resources :games
  resources :cards
  resources :game_player_cards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  validates :title, uniqueness: { case_sensitive: false }

  def fields
    ('1'..'12').map { |n| send("slot_#{n}".to_sym) }
  end
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  has_many :game_cards
  has_many :cards, through: :game_cards
  has_many :game_players
end

app/models/game_card.rb
# frozen_string_literal: true

## Card in a game context
class GameCard < ApplicationRecord
  belongs_to :game
  belongs_to :card
end

app/models/game_player.rb
# frozen_string_literal: true

## Player in a game context
class GamePlayer < ApplicationRecord
  belongs_to :game
  has_many :game_player_cards, foreign_key: :player_id

  # look for existing user for this game
  # if none, create it
  def self.find_or_make(game_id, session_id)
    GamePlayer.where(
      session_id: session_id,
      game_id: game_id
    ).first_or_create
  end
end

app/models/game_player_card.rb
# frozen_string_literal: true

## Player answers for a card in a game
class GamePlayerCard < ApplicationRecord
  belongs_to :game_player, foreign_key: :player_id
  belongs_to :card

  # look for existing user for this game
  # if none, create it
  def self.find_or_make(player_id, game_id)
    sql = <<~SQL
      SELECT gpc.*
        FROM game_player_cards gpc,
             games g
       WHERE gpc.player_id = :player_id
         AND g.id = :game_id
         AND g.active_card_id = gpc.card_id
    SQL

    game_player_card = GamePlayerCard.find_by_sql([sql, { player_id: player_id, game_id: game_id }]).first

    unless game_player_card
      @game = Game.find game_id
      game_player_card = GamePlayerCard.create(player_id: player_id, card_id: @game.active_card_id)
    end

    game_player_card
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  before_action :set_card, only: %i[show edit update destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show; end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit; end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_card
    @card = Card.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def card_params
    params.require(:card).permit(:title, :slot_1, :slot_2, :slot_3, :slot_4, :slot_5, :slot_6, :slot_7, :slot_8, :slot_9, :slot_10, :slot_11, :slot_12, :notes)
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show; end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit; end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:title, :locator, card_ids: [])
  end
end

app/controllers/play_controller.rb
# frozen_string_literal: true

class PlayController < ApplicationController
  def join
    @game = Game.where(locator: params[:locator]).first
    return unless join_check

    @player = GamePlayer.find_or_make(@game.id, session_id)
    return unless @player.name

    @game_player_card = GamePlayerCard.find_or_make(@player.id, @game.id)
    render 'play'
    nil
  end

  def play
    @game = Game.find(params[:game_id])
    @player = GamePlayer.find(params[:player_id])
    @game_player_card = GamePlayerCard.find_or_make(@player.id, @game.id)

    return if @player.name

    @player.name = params[:name]
    @player.save!
  end

  def entries
    # confirm session.id
    @game_player_card = GamePlayerCard.find params[:game_player_card_id]
    return unless session_id == @game_player_card.game_player.session_id

    persist_entries

    @game = @game_player_card.game_player.game
    @player = @game_player_card.game_player
    render :play
  end

  private

  # for testing -- we don't have users login so this is not set by devise
  # but overridden in the system test
  def session_id
    session.id.to_s
  end

  def persist_entries
    @game_player_card.attributes = game_player_card_params
    @game_player_card.save!
    flash.now[:notice] = "Answers saved at #{DateTime.now.strftime('%I:%M:%S %p')}"
  end

  # validation
  def join_check
    unless @game
      flash.now[:notice] = "Game #{params[:locator]} does not exist"
      return false
    end
    true
  end

  # Only allow a list of trusted parameters through.
  def game_player_card_params
    params.permit(:slot_1, :slot_2, :slot_3, :slot_4, :slot_5, :slot_6, :slot_7, :slot_8, :slot_9, :slot_10, :slot_11, :slot_12, :locator)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cards_helper.rb
# frozen_string_literal: true

module CardsHelper
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/helpers/play_helper.rb
# frozen_string_literal: true

module PlayHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :slot_1 %>
    <%= form.text_field :slot_1 %>
  </div>

  <div class="field">
    <%= form.label :slot_2 %>
    <%= form.text_field :slot_2 %>
  </div>

  <div class="field">
    <%= form.label :slot_3 %>
    <%= form.text_field :slot_3 %>
  </div>

  <div class="field">
    <%= form.label :slot_4 %>
    <%= form.text_field :slot_4 %>
  </div>

  <div class="field">
    <%= form.label :slot_5 %>
    <%= form.text_field :slot_5 %>
  </div>

  <div class="field">
    <%= form.label :slot_6 %>
    <%= form.text_field :slot_6 %>
  </div>

  <div class="field">
    <%= form.label :slot_7 %>
    <%= form.text_field :slot_7 %>
  </div>

  <div class="field">
    <%= form.label :slot_8 %>
    <%= form.text_field :slot_8 %>
  </div>
  <div class="field">
    <%= form.label :slot_9 %>
    <%= form.text_field :slot_9 %>
  </div>

  <div class="field">
    <%= form.label :slot_10 %>
    <%= form.text_field :slot_10 %>
  </div>

  <div class="field">
    <%= form.label :slot_11 %>
    <%= form.text_field :slot_11 %>
  </div>

  <div class="field">
    <%= form.label :slot_12 %>
    <%= form.text_field :slot_12 %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

# <%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= link_to card.title, card %></td>
        <td><%= card.notes %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path, class: 'btn btn-primary' %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @card.title %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @card.notes %>
</p>

<ol>
  <% @card.fields.each do |f| %>
    <li><%= f %></li>
  <% end %>
</ol>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <%= stylesheet_link_tag 'games', media: 'all', 'data-turbolinks-track': 'reload' %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :locator %>
    <%= form.text_field :locator %>
  </div>

  <div class="cards">
    <h3>Cards</h3>
      <ul>
        <%= form.collection_check_boxes :card_ids, Card.all, :id, :title do |cb| %>
          <li><%= cb.label(class: 'label-checkbox') { cb.check_box + cb.text } %></li>
        <% end %>
      </ul>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Locator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.title, game %></td>
        <td><%= game.locator %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path, class: 'btn btn-primary' %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>Locator:</strong>
  <%= @game.locator %>
</p>

<p>
  <strong>Cards:</strong>
  <ul class="list-group">
    <% @game.cards.each do |c| %>
       <li class="list-group-item"><%= link_to c.title, c %></li>
    <% end %>
  </ul>
</p>

<p>
  <h3>Players</h3>
  <% @game.game_players.each do |player| %>
    <ul class="list-group">
      <li class="list-group-item"><%= link_to player.name, '' %></li>
    </ul>
  <% end %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scoottergaries</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='container'>
    <%= yield %>
  </body>
</html>

app/views/play/join.html.erb
<% if @game %>
  <h1><%= @game.title %></h1>
  <%= form_with(local: true, url: play_play_path) do |form| %>
    <% if @game.active_card_id %>
      <div class="field">
        <% if @player.name %>
          <h2><%= @player.name %></h2>
        <% else %>
          <%= form.label :name %>
          <%= form.text_field :name %>
        <% end %>
        <%= hidden_field_tag(:game_id, @game.id) %>
        <%= hidden_field_tag(:player_id, @player.id) %>
      </div>

      <div class="actions">
        <%= form.submit 'Join Game' %>
      </div>
    <% end %>
  <% end %>
<% end %>

<p id="notice" class="alert-warning"><%= notice %></p>

app/views/play/play.html.erb
<p id="notice" class="alert-warning"><%= notice %></p>
<h1><%= @game.title %> | <%= @player.name %> | <%= session.id %> </h1>

<% @game.cards.each do |c| %>
  <div>
    <h2><%= c.title %></h2>
    <% if @game_player_card %>
      <%= form_with(local: true, url: play_entries_path(@game_player_card.id)) do |form| %>
        <% c.fields.each_with_index do |f, i| %>
          <div class="field">
            <%= form.label f %>
            <%= form.text_field "slot_#{i + 1}", value: @game_player_card.send("slot_#{i + 1}".to_sym) %>
          </div>
        <% end %>
        <div class="actions">
          <%= form.submit 'Submit Answers' %>
        </div>
      <% end %>
    <% else %>
      <h2>Pick a card</h2>
    <% end %>
    <%= hidden_field_tag(:game_id, @game.id) %>
    <%= hidden_field_tag(:player_id, @player.id) %>
  </div>
<% end %>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>